#!/bin/bash

Main() {
	source /usr/share/endeavouros/scripts/eos-script-lib-yad || return 1

	local command=(
		eos_yad --title="EndeavourOS i3-wm keybindings:" --no-buttons --geometry=500x400-50-400 --list
		--column=key: --column=description: --column=command:
		"ESC" "close this app" ""
		"=" "modkey" "(set mod Mod4)"
		"+enter" "open a terminal" ""
		"" "app menu" ""
		"+d" "app menu" ""
		"+w" "rofi window" ""
		"+r" "rofi run" ""
		"+q" "close focused app" ""
		"+shift+p" "cpu profiles" "l"
		"+shift+g" "gpu profile" "l"
		"+shift+n" "gpu offload(hybrid)" "l"
		"+Shift+e" "session menu" ""
		"Print-key" "screenshot" ""
		"F1" "open this menu" ""
	)

	"${command[@]}"
}

Main "$@"
